source 'https://github.com/CocoaPods/Specs.git'

target 'RJImageLoader', :exclusive => true do
  pod "RJImageLoader", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RJImageLoader", :path => "../"

  
end
